export const seoConfig = {
  en: {
    title: "Arc Raiders Database - Complete Item Guide & Crafting Recipes",
    description: "Arc Raiders Database: 485+ items with crafting recipes, recycling guides & stats. Search & filter weapons, materials, and equipment.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Database",
      "Arc Raiders Items",
      "Arc Raiders Crafting",
      "Arc Raiders Recipes",
      "Arc Raiders Guide",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Recycling Guide",
      "Item Stats",
      "Loot Guide",
      "Arc Raiders Weapons",
      "Arc Raiders Materials",
      "Arc Raiders Equipment",
    ],
    ogTitle: "Arc Raiders Database - Complete Item Guide & Crafting Recipes",
    ogDescription: "Arc Raiders Database: 485+ items with crafting recipes, recycling guides & stats.",
    twitterTitle: "Arc Raiders Database - Complete Item Guide",
    twitterDescription: "Arc Raiders Database: 485+ items with crafting recipes, recycling guides & stats.",
  },
  fr: {
    title: "Base de Données Arc Raiders - Guide Complet des Objets et Recettes d'Artisanat",
    description: "Base de Données Arc Raiders: 485+ objets avec recettes d'artisanat, guides de recyclage et statistiques. Recherchez et filtrez les armes, matériaux et équipements.",
    keywords: [
      "Arc Raiders",
      "Base de Données Arc Raiders",
      "Objets Arc Raiders",
      "Artisanat Arc Raiders",
      "Recettes Arc Raiders",
      "Guide Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Guide de Recyclage",
      "Statistiques des Objets",
      "Guide de Butin",
      "Armes Arc Raiders",
      "Matériaux Arc Raiders",
      "Équipement Arc Raiders",
    ],
    ogTitle: "Base de Données Arc Raiders - Guide Complet des Objets",
    ogDescription: "Base de Données Arc Raiders: 485+ objets avec recettes d'artisanat et guides de recyclage.",
    twitterTitle: "Base de Données Arc Raiders - Guide Complet",
    twitterDescription: "Base de Données Arc Raiders: 485+ objets avec recettes d'artisanat.",
  },
  de: {
    title: "Arc Raiders Datenbank - Vollständiger Gegenstandsleitfaden und Herstellungsrezepte",
    description: "Arc Raiders Datenbank: 485+ Gegenstände mit Herstellungsrezepten, Recycling-Anleitungen und Statistiken. Durchsuchen und filtern Sie Waffen, Materialien und Ausrüstung.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Datenbank",
      "Arc Raiders Gegenstände",
      "Arc Raiders Herstellung",
      "Arc Raiders Rezepte",
      "Arc Raiders Leitfaden",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Recycling-Leitfaden",
      "Gegenstands-Statistiken",
      "Loot-Leitfaden",
      "Arc Raiders Waffen",
      "Arc Raiders Materialien",
      "Arc Raiders Ausrüstung",
    ],
    ogTitle: "Arc Raiders Datenbank - Vollständiger Gegenstandsleitfaden",
    ogDescription: "Arc Raiders Datenbank: 485+ Gegenstände mit Herstellungsrezepten und Recycling-Anleitungen.",
    twitterTitle: "Arc Raiders Datenbank - Vollständiger Leitfaden",
    twitterDescription: "Arc Raiders Datenbank: 485+ Gegenstände mit Herstellungsrezepten.",
  },
  es: {
    title: "Base de Datos de Arc Raiders - Guía Completa de Objetos y Recetas de Fabricación",
    description: "Base de Datos de Arc Raiders: 485+ objetos con recetas de fabricación, guías de reciclaje y estadísticas. Busque y filtre armas, materiales y equipos.",
    keywords: [
      "Arc Raiders",
      "Base de Datos Arc Raiders",
      "Objetos Arc Raiders",
      "Fabricación Arc Raiders",
      "Recetas Arc Raiders",
      "Guía Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Guía de Reciclaje",
      "Estadísticas de Objetos",
      "Guía de Botín",
      "Armas Arc Raiders",
      "Materiales Arc Raiders",
      "Equipos Arc Raiders",
    ],
    ogTitle: "Base de Datos de Arc Raiders - Guía Completa de Objetos",
    ogDescription: "Base de Datos de Arc Raiders: 485+ objetos con recetas de fabricación y guías de reciclaje.",
    twitterTitle: "Base de Datos de Arc Raiders - Guía Completa",
    twitterDescription: "Base de Datos de Arc Raiders: 485+ objetos con recetas de fabricación.",
  },
  pt: {
    title: "Banco de Dados do Arc Raiders - Guia Completo de Itens e Receitas de Fabricação",
    description: "Banco de Dados do Arc Raiders: 485+ itens com receitas de fabricação, guias de reciclagem e estatísticas. Pesquise e filtre armas, materiais e equipamentos.",
    keywords: [
      "Arc Raiders",
      "Banco de Dados Arc Raiders",
      "Itens Arc Raiders",
      "Fabricação Arc Raiders",
      "Receitas Arc Raiders",
      "Guia Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Guia de Reciclagem",
      "Estatísticas de Itens",
      "Guia de Saque",
      "Armas Arc Raiders",
      "Materiais Arc Raiders",
      "Equipamentos Arc Raiders",
    ],
    ogTitle: "Banco de Dados do Arc Raiders - Guia Completo de Itens",
    ogDescription: "Banco de Dados do Arc Raiders: 485+ itens com receitas de fabricação e guias de reciclagem.",
    twitterTitle: "Banco de Dados do Arc Raiders - Guia Completo",
    twitterDescription: "Banco de Dados do Arc Raiders: 485+ itens com receitas de fabricação.",
  },
  pl: {
    title: "Baza Danych Arc Raiders - Kompletny Przewodnik Przedmiotów i Przepisy Rzemieślnicze",
    description: "Baza Danych Arc Raiders: 485+ przedmiotów z przepisami rzemieślniczymi, przewodnikami recyklingu i statystykami. Wyszukuj i filtruj broń, materiały i sprzęt.",
    keywords: [
      "Arc Raiders",
      "Baza Danych Arc Raiders",
      "Przedmioty Arc Raiders",
      "Rzemiosło Arc Raiders",
      "Przepisy Arc Raiders",
      "Przewodnik Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Przewodnik Recyklingu",
      "Statystyki Przedmiotów",
      "Przewodnik Łupów",
      "Broń Arc Raiders",
      "Materiały Arc Raiders",
      "Sprzęt Arc Raiders",
    ],
    ogTitle: "Baza Danych Arc Raiders - Kompletny Przewodnik Przedmiotów",
    ogDescription: "Baza Danych Arc Raiders: 485+ przedmiotów z przepisami rzemieślniczymi i przewodnikami recyklingu.",
    twitterTitle: "Baza Danych Arc Raiders - Kompletny Przewodnik",
    twitterDescription: "Baza Danych Arc Raiders: 485+ przedmiotów z przepisami rzemieślniczymi.",
  },
  no: {
    title: "Arc Raiders Database - Komplett Gjenstands Veiledning og Oppskrifter",
    description: "Arc Raiders Database: 485+ gjenstander med oppskrifter, resirkleringsveiledninger og statistikk. Søk og filtrer våpen, materialer og utstyr.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Database",
      "Arc Raiders Gjenstander",
      "Arc Raiders Håndverk",
      "Arc Raiders Oppskrifter",
      "Arc Raiders Veiledning",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Resirkleringsveiledning",
      "Gjenstands Statistikk",
      "Bytteveildedning",
      "Arc Raiders Våpen",
      "Arc Raiders Materialer",
      "Arc Raiders Utstyr",
    ],
    ogTitle: "Arc Raiders Database - Komplett Gjenstands Veiledning",
    ogDescription: "Arc Raiders Database: 485+ gjenstander med oppskrifter og resirkleringsveiledninger.",
    twitterTitle: "Arc Raiders Database - Komplett Veiledning",
    twitterDescription: "Arc Raiders Database: 485+ gjenstander med oppskrifter.",
  },
  da: {
    title: "Arc Raiders Database - Komplet Genstands Guide og Opskrifter",
    description: "Arc Raiders Database: 485+ genstande med opskrifter, genbrugsvejledninger og statistikker. Søg og filtrer våben, materialer og udstyr.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Database",
      "Arc Raiders Genstande",
      "Arc Raiders Håndværk",
      "Arc Raiders Opskrifter",
      "Arc Raiders Guide",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Genbrugsvejledning",
      "Genstands Statistikker",
      "Byttevejledning",
      "Arc Raiders Våben",
      "Arc Raiders Materialer",
      "Arc Raiders Udstyr",
    ],
    ogTitle: "Arc Raiders Database - Komplet Genstands Guide",
    ogDescription: "Arc Raiders Database: 485+ genstande med opskrifter og genbrugsvejledninger.",
    twitterTitle: "Arc Raiders Database - Komplet Guide",
    twitterDescription: "Arc Raiders Database: 485+ genstande med opskrifter.",
  },
  it: {
    title: "Database Arc Raiders - Guida Completa degli Oggetti e Ricette di Creazione",
    description: "Database Arc Raiders: 485+ oggetti con ricette di creazione, guide al riciclaggio e statistiche. Cerca e filtra armi, materiali e attrezzature.",
    keywords: [
      "Arc Raiders",
      "Database Arc Raiders",
      "Oggetti Arc Raiders",
      "Creazione Arc Raiders",
      "Ricette Arc Raiders",
      "Guida Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Guida al Riciclaggio",
      "Statistiche degli Oggetti",
      "Guida al Bottino",
      "Armi Arc Raiders",
      "Materiali Arc Raiders",
      "Attrezzature Arc Raiders",
    ],
    ogTitle: "Database Arc Raiders - Guida Completa degli Oggetti",
    ogDescription: "Database Arc Raiders: 485+ oggetti con ricette di creazione e guide al riciclaggio.",
    twitterTitle: "Database Arc Raiders - Guida Completa",
    twitterDescription: "Database Arc Raiders: 485+ oggetti con ricette di creazione.",
  },
  ru: {
    title: "База Данных Arc Raiders - Полное Руководство Предметов и Рецепты Крафта",
    description: "База Данных Arc Raiders: 485+ предметов с рецептами крафта, руководствами переработки и статистикой. Ищите и фильтруйте оружие, материалы и снаряжение.",
    keywords: [
      "Arc Raiders",
      "База Данных Arc Raiders",
      "Предметы Arc Raiders",
      "Крафт Arc Raiders",
      "Рецепты Arc Raiders",
      "Руководство Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Руководство Переработки",
      "Статистика Предметов",
      "Руководство Добычи",
      "Оружие Arc Raiders",
      "Материалы Arc Raiders",
      "Снаряжение Arc Raiders",
    ],
    ogTitle: "База Данных Arc Raiders - Полное Руководство Предметов",
    ogDescription: "База Данных Arc Raiders: 485+ предметов с рецептами крафта и руководствами переработки.",
    twitterTitle: "База Данных Arc Raiders - Полное Руководство",
    twitterDescription: "База Данных Arc Raiders: 485+ предметов с рецептами крафта.",
  },
  ja: {
    title: "Arc Raidersデータベース - 完全なアイテムガイドとクラフトレシピ",
    description: "Arc Raidersデータベース: 485+アイテム、クラフトレシピ、リサイクルガイド、統計情報。武器、素材、装備を検索・フィルタリング。",
    keywords: [
      "Arc Raiders",
      "Arc Raidersデータベース",
      "Arc Raidersアイテム",
      "Arc Raidersクラフト",
      "Arc Raidersレシピ",
      "Arc Raidersガイド",
      "Arc Raiders Wiki",
      "Embark Studios",
      "リサイクルガイド",
      "アイテム統計",
      "ルートガイド",
      "Arc Raiders武器",
      "Arc Raiders素材",
      "Arc Raiders装備",
    ],
    ogTitle: "Arc Raidersデータベース - 完全なアイテムガイド",
    ogDescription: "Arc Raidersデータベース: 485+アイテムとクラフトレシピ。",
    twitterTitle: "Arc Raidersデータベース - 完全ガイド",
    twitterDescription: "Arc Raidersデータベース: 485+アイテム。",
  },
  'zh-TW': {
    title: "Arc Raiders資料庫 - 完整物品指南和製作食譜",
    description: "Arc Raiders資料庫: 485+物品，附製作食譜、回收指南和統計資訊。搜尋和篩選武器、材料和裝備。",
    keywords: [
      "Arc Raiders",
      "Arc Raiders資料庫",
      "Arc Raiders物品",
      "Arc Raiders製作",
      "Arc Raiders食譜",
      "Arc Raiders指南",
      "Arc Raiders維基",
      "Embark Studios",
      "回收指南",
      "物品統計",
      "掠奪指南",
      "Arc Raiders武器",
      "Arc Raiders材料",
      "Arc Raiders裝備",
    ],
    ogTitle: "Arc Raiders資料庫 - 完整物品指南",
    ogDescription: "Arc Raiders資料庫: 485+物品與製作食譜。",
    twitterTitle: "Arc Raiders資料庫 - 完整指南",
    twitterDescription: "Arc Raiders資料庫: 485+物品。",
  },
  uk: {
    title: "База Даних Arc Raiders - Повний Посібник Предметів та Рецепти Крафту",
    description: "База Даних Arc Raiders: 485+ предметів з рецептами крафту, посібниками переробки та статистикою. Шукайте та фільтруйте зброю, матеріали та спорядження.",
    keywords: [
      "Arc Raiders",
      "База Даних Arc Raiders",
      "Предмети Arc Raiders",
      "Крафт Arc Raiders",
      "Рецепти Arc Raiders",
      "Посібник Arc Raiders",
      "Wiki Arc Raiders",
      "Embark Studios",
      "Посібник Переробки",
      "Статистика Предметів",
      "Посібник Здобичі",
      "Зброя Arc Raiders",
      "Матеріали Arc Raiders",
      "Спорядження Arc Raiders",
    ],
    ogTitle: "База Даних Arc Raiders - Повний Посібник Предметів",
    ogDescription: "База Даних Arc Raiders: 485+ предметів з рецептами крафту та посібниками переробки.",
    twitterTitle: "База Даних Arc Raiders - Повний Посібник",
    twitterDescription: "База Даних Arc Raiders: 485+ предметів з рецептами крафту.",
  },
  'zh-CN': {
    title: "Arc Raiders数据库 - 完整物品指南和制作配方",
    description: "Arc Raiders数据库: 485+物品，含制作配方、回收指南和统计信息。搜索和筛选武器、材料和装备。",
    keywords: [
      "Arc Raiders",
      "Arc Raiders数据库",
      "Arc Raiders物品",
      "Arc Raiders制作",
      "Arc Raiders配方",
      "Arc Raiders指南",
      "Arc Raiders维基",
      "Embark Studios",
      "回收指南",
      "物品统计",
      "掠夺指南",
      "Arc Raiders武器",
      "Arc Raiders材料",
      "Arc Raiders装备",
    ],
    ogTitle: "Arc Raiders数据库 - 完整物品指南",
    ogDescription: "Arc Raiders数据库: 485+物品与制作配方。",
    twitterTitle: "Arc Raiders数据库 - 完整指南",
    twitterDescription: "Arc Raiders数据库: 485+物品。",
  },
  kr: {
    title: "Arc Raiders 데이터베이스 - 완전한 아이템 가이드 및 제작 레시피",
    description: "Arc Raiders 데이터베이스: 485+개 아이템, 제작 레시피, 재활용 가이드 및 통계. 무기, 재료 및 장비 검색 및 필터링.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders 데이터베이스",
      "Arc Raiders 아이템",
      "Arc Raiders 제작",
      "Arc Raiders 레시피",
      "Arc Raiders 가이드",
      "Arc Raiders 위키",
      "Embark Studios",
      "재활용 가이드",
      "아이템 통계",
      "전리품 가이드",
      "Arc Raiders 무기",
      "Arc Raiders 재료",
      "Arc Raiders 장비",
    ],
    ogTitle: "Arc Raiders 데이터베이스 - 완전한 아이템 가이드",
    ogDescription: "Arc Raiders 데이터베이스: 485+개 아이템 및 제작 레시피.",
    twitterTitle: "Arc Raiders 데이터베이스 - 완전한 가이드",
    twitterDescription: "Arc Raiders 데이터베이스: 485+개 아이템.",
  },
  tr: {
    title: "Arc Raiders Veritabanı - Eksiksiz Eşya Rehberi ve Craft Reçeteleri",
    description: "Arc Raiders Veritabanı: 485+ eşya, craft reçeteleri, geri dönüşüm kılavuzları ve istatistikler. Silahları, malzemeleri ve donanımı arayın ve filtreleyin.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Veritabanı",
      "Arc Raiders Eşyaları",
      "Arc Raiders Craft",
      "Arc Raiders Reçeteleri",
      "Arc Raiders Rehberi",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Geri Dönüşüm Kılavuzu",
      "Eşya İstatistikleri",
      "Hazine Rehberi",
      "Arc Raiders Silahları",
      "Arc Raiders Malzemeleri",
      "Arc Raiders Donanımı",
    ],
    ogTitle: "Arc Raiders Veritabanı - Eksiksiz Eşya Rehberi",
    ogDescription: "Arc Raiders Veritabanı: 485+ eşya ve craft reçeteleri.",
    twitterTitle: "Arc Raiders Veritabanı - Eksiksiz Rehber",
    twitterDescription: "Arc Raiders Veritabanı: 485+ eşya.",
  },
  hr: {
    title: "Arc Raiders Baza Podataka - Kompletan Vodič Predmeta i Recepti za Izradu",
    description: "Arc Raiders Baza Podataka: 485+ predmeta s receptima za izradu, vodiči za reciklažu i statistike. Pretražite i filtrirajte oružje, materijale i opremu.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Baza Podataka",
      "Arc Raiders Predmeti",
      "Arc Raiders Izrada",
      "Arc Raiders Recepti",
      "Arc Raiders Vodič",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Vodič za Reciklažu",
      "Statistike Predmeta",
      "Vodič za Pljačku",
      "Arc Raiders Oružje",
      "Arc Raiders Materijali",
      "Arc Raiders Oprema",
    ],
    ogTitle: "Arc Raiders Baza Podataka - Kompletan Vodič Predmeta",
    ogDescription: "Arc Raiders Baza Podataka: 485+ predmeta s receptima za izradu i vodiči za reciklažu.",
    twitterTitle: "Arc Raiders Baza Podataka - Kompletan Vodič",
    twitterDescription: "Arc Raiders Baza Podataka: 485+ predmeta.",
  },
  sr: {
    title: "Arc Raiders Baza Podataka - Kompletan Vodič Predmeta i Recepti za Kreiranje",
    description: "Arc Raiders Baza Podataka: 485+ predmeta sa receptima za kreiranje, vodiči za reciklažu i statistike. Pretražite i filtrirajte oružje, materijale i opremu.",
    keywords: [
      "Arc Raiders",
      "Arc Raiders Baza Podataka",
      "Arc Raiders Predmeti",
      "Arc Raiders Kreiranje",
      "Arc Raiders Recepti",
      "Arc Raiders Vodič",
      "Arc Raiders Wiki",
      "Embark Studios",
      "Vodič za Reciklažu",
      "Statistike Predmeta",
      "Vodič za Pljačku",
      "Arc Raiders Oružje",
      "Arc Raiders Materijali",
      "Arc Raiders Oprema",
    ],
    ogTitle: "Arc Raiders Baza Podataka - Kompletan Vodič Predmeta",
    ogDescription: "Arc Raiders Baza Podataka: 485+ predmeta sa receptima za kreiranje i vodiči za reciklažu.",
    twitterTitle: "Arc Raiders Baza Podataka - Kompletan Vodič",
    twitterDescription: "Arc Raiders Baza Podataka: 485+ predmeta.",
  },
};

export type Language = 'en' | 'fr' | 'de' | 'es' | 'pt' | 'pl' | 'no' | 'da' | 'it' | 'ru' | 'ja' | 'zh-TW' | 'uk' | 'zh-CN' | 'kr' | 'tr' | 'hr' | 'sr';

export function getSEOConfig(lang: Language = 'en') {
  return seoConfig[lang] || seoConfig.en;
}
